# Introduction to Numpy

1 : Basic Description of Numpy:-
Numpy's most useful feature is it is capable of producing and tackaling n dimentional array object. It is also called as ndarray. It is heavily used in Scientific computing. It is written in C, and C++. 

2 : Main benifits of using Numpy array over a Python list:-
    a --> Less Memory
    b --> Fast
    c --> Convinient

In [1]:
# Importing the necessary librarires
import numpy as np

In [2]:
# Comparing the numpy with a python list :
import time
import sys

In [3]:
lst = range(1000)
arr = np.arange(1000)

In [4]:
# Checking the memorysize consuming by the list and Array  ---  Numpy consumes very less memory compared to Python List
print("Size of Python List",sys.getsizeof(lst[0])*len(lst))
print("Size of numpy array ",arr.itemsize*arr.size)

Size of Python List 24000
Size of numpy array  4000


In [5]:
# Python List vs Python Array time processing

# Basic Usage Of Numpy

In [6]:
# Creation of numpy array from list
arr0 = np.array([1,2,4,'a'])
arr1 = np.array([2,3,4,5])
arr2 = np.array([1,2,6,6])
arrangearray = np.arange(1,11)
print(arrangearray)
# Above all the arrays are one dimensional array

[ 1  2  3  4  5  6  7  8  9 10]


In [7]:
# Checking the type of the numpy array
type(arr1)

numpy.ndarray

In [8]:
# Numpy basic mathematical operation
arr3 = arr1 + arr2
arr4 = arr1 - arr2
arr5 = arr1 * arr2

In [9]:
# Printing mathematical results
print("Sum Result", arr3)
print("Substraction result", arr4)
print("Multiplication Result", arr5)

Sum Result [ 3  5 10 11]
Substraction result [ 1  1 -2 -1]
Multiplication Result [ 2  6 24 30]


# Numpy basic array operation
Arrays are quite simmilar to matrix

In [28]:
# Create 2D / Two Dimension array
twodarray = np.array([[1,2,3,4],[4,5,6,7]]) 

In [29]:
print("Two Dimenssion Array : \n",twodarray)

Two Dimenssion Array : 
 [[1 2 3 4]
 [4 5 6 7]]


In [30]:
# Check the dimension of any numpy array
print(twodarray.ndim)

2


In [31]:
# check the size of the numpy array 
twodarray.itemsize   # -----------> Item size print the byte size of the each array

4

In [32]:
# Check the current data type of the array
twodarray.dtype

dtype('int32')

In [33]:
# Special case ---> All data types are not same
arr0.dtype

dtype('<U11')

In [35]:
# Initialize the data type while creating the numpy array
array = np.array([1,2,3], dtype=np.float64)
print(array.dtype)
print(array.itemsize) # Each float variable takes 8 bytes

float64
8


In [36]:
# Check the shape of the array
print(array.shape)
print(twodarray.shape)

(3,)
(2, 4)


In [18]:
# Complex data type 
complexarray = np.array([1,2,3], dtype=complex)
print(complexarray)

[1.+0.j 2.+0.j 3.+0.j]


In [37]:
#Fill up the array with same numbers
zeroarray = np.zeros((2,3)) # Shape should be passed
print(zeroarray,'\n')
onearray = np.ones((3,4))
print(onearray,'\n')

[[0. 0. 0.]
 [0. 0. 0.]] 

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]] 



In [38]:
# Reshaping any array
array = np.array([[1,3],[4,5],[6,7]])
print(array.shape)
print(array)
array = array.reshape(2,3) # Reshaped array shape should be passed , and that shape must be compatible
print(array)

(3, 2)
[[1 3]
 [4 5]
 [6 7]]
[[1 3 4]
 [5 6 7]]


In [41]:
# array.ravel function --> It flatters any n dimension array into an one dimensional array
array1 = array.ravel()
print(array1)

[1 3 4 5 6 7]


In [40]:
# Min - Max - sum operation in array 
print(array.min())
print(array.max())
print(array.sum())

1
7
26


In [23]:
# Axis wise sumation ----------- axis = 0 - columns, axis =1 - rows
print("Main array \n",array,"\n")
print("Column wise sumation",array.sum(axis=0),"\n")
print("Row wise sumation",array.sum(axis=1))

Main array 
 [[1 3 4]
 [5 6 7]] 

Column wise sumation [ 6  9 11] 

Row wise sumation [ 8 18]


In [42]:
# Find the square root of the any numpy array
"""Syntax --> np.sqrt(array_name)"""
np.sqrt(array)

array([[1.        , 1.73205081, 2.        ],
       [2.23606798, 2.44948974, 2.64575131]])

# Statistical operation using numpy array 

In [43]:
# Find the standard deviation of elements existinf in that numpy array
"""Syntax -- > np.std(array_name)"""
np.std(array)

1.9720265943665387

# Matrix operation using numpy array

In [49]:
ar1 = np.array([[1,0,0],[0,1,0],[0,0,1]])
ar2 = np.array([[1,2,3],[1,2,3],[1,2,3]])
print("< -- Array 1 -- > \n",ar1,"\n")
print("< -- Array 2 -- > \n",ar2,"\n")
sum_array = ar1 + ar2
sub_array = ar1 - ar2
div_array = ar1 / ar2

# Matix dot Product
dot_product = ar1.dot(ar2)

# Matrix cross Product
cross_product = np.cross(ar1,ar2)

# Printing the matrix operation results
print("Sum \n",sum_array,"\n")
print("substraction \n",sub_array,"\n")
print("Division \n",div_array,"\n")
print("Dot product \n",dot_product,"\n")
print("Crosss Product \n",cross_product,"\n")


< -- Array 1 -- > 
 [[1 0 0]
 [0 1 0]
 [0 0 1]] 

< -- Array 2 -- > 
 [[1 2 3]
 [1 2 3]
 [1 2 3]] 

Sum 
 [[2 2 3]
 [1 3 3]
 [1 2 4]] 

substraction 
 [[ 0 -2 -3]
 [-1 -1 -3]
 [-1 -2 -2]] 

Division 
 [[1.         0.         0.        ]
 [0.         0.5        0.        ]
 [0.         0.         0.33333333]] 

Dot product 
 [[1 2 3]
 [1 2 3]
 [1 2 3]] 

Crosss Product 
 [[ 0 -3  2]
 [ 3  0 -1]
 [-2  1  0]] 



#  Slicing, Iterating through arrays, Stacking together two arrays, indexing with boolean arrays

In [71]:
# Slicing of numpy array : It is quite simmilar to list slicing
lst = [12,2,4]
array1 = np.array([1,2,3,4])
array2 = np.array([[1,2,3],[4,5,6],[7,8,9]]) 

print(array1,"\n")
print(array2,"\n")

# List slicing
print("Slicing of the list -------- >",lst[0:2],"\n")

# Numpy array slicing
print("Slicing of the numpy oned array --------- >",array1[0:3],"\n")
print("Slicing of numpy threed(3-D) array row wise-------- >\n",array2[0:2],"\n") # Row wise slicing will occur


# Column wise slicing
print("Column wise slicing --- >\n",array2[-1],"\n")
print(array2[:,1:],"\n") # Syntax : Numpy array slicing[row,column]
print("Printing particular columns \n",array2[:,[0,2]])

[1 2 3 4] 

[[1 2 3]
 [4 5 6]
 [7 8 9]] 

Slicing of the list -------- > [12, 2] 

Slicing of the numpy oned array --------- > [1 2 3] 

Slicing of numpy threed(3-D) array row wise-------- >
 [[1 2 3]
 [4 5 6]] 

Column wise slicing --- >
 [7 8 9] 

[[2 3]
 [5 6]
 [8 9]] 

Printing particular columns 
 [[1 3]
 [4 6]
 [7 9]]


In [75]:
# Using loop for slicing
for rows in array2:
    print(rows,type(rows))
    
for rows in array2:
    for elements in rows:
        print(elements)

[1 2 3] <class 'numpy.ndarray'>
[4 5 6] <class 'numpy.ndarray'>
[7 8 9] <class 'numpy.ndarray'>
1
2
3
4
5
6
7
8
9


In [77]:
# Using flat method to itterate the array using single loop
for elements in array2.flat:
    print(elements)

1
2
3
4
5
6
7
8
9


In [87]:
# Stacking two arrays together
ar1 = np.arange(0,6).reshape(3,2)
ar2 = np.arange(6,12).reshape(3,2)

print(ar1,"\n")
print(ar2,"\n")

# vertical stacking
ar3 = np.vstack((ar1,ar2))  # two arrays should be passed inside a tuple  --- Syntax : np.vstack((array1,array2))
print(ar3,"\n")

#Horizontal stacking
ar4 = np.hstack((ar1,ar2))
print(ar4,"\n")


#Vertical spliting of array
print(np.vsplit(ar3,3))


# Horizontal spliting of two array
print("\n",np.hsplit(ar4,2))

[[0 1]
 [2 3]
 [4 5]] 

[[ 6  7]
 [ 8  9]
 [10 11]] 

[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]] 

[[ 0  1  6  7]
 [ 2  3  8  9]
 [ 4  5 10 11]] 

[array([[0, 1],
       [2, 3]]), array([[4, 5],
       [6, 7]]), array([[ 8,  9],
       [10, 11]])]

 [array([[0, 1],
       [2, 3],
       [4, 5]]), array([[ 6,  7],
       [ 8,  9],
       [10, 11]])]


In [102]:
# Boolean indexing
"""
Qs : Suppose there is a numpy 3d array, filled up with some elements , now find out those elements which 
     are greater thann 10
"""
array = np.arange(0,21).reshape(3,7)
print(array)
booindex = array>10
print("\n",booindex)

arr2 = array[booindex] # It is returning only those values where index value is True
print("\n",arr2)

[[ 0  1  2  3  4  5  6]
 [ 7  8  9 10 11 12 13]
 [14 15 16 17 18 19 20]]

 [[False False False False False False False]
 [False False False False  True  True  True]
 [ True  True  True  True  True  True  True]]

 [11 12 13 14 15 16 17 18 19 20]
